algorithm: fixmatch_distill
resume: True
overwrite: True
use_wandb: True
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024
num_log_iter: 256
num_labels: 700
batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 2
ema_m: 0.999
crop_ratio: 0.875
img_size: 64
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: eurosat
train_sampler: RandomSampler
num_classes: 10
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10248
dist_backend: nccl
gpu: None
lb_imb_ratio: 100
ulb_imb_ratio: -100
ulb_num_labels: 1400
imb_algorithm: adello
adello_alpha_min: 0.1
adello_k: 2.0
adello_alpha_from_epoch: False
distill_complement: True
imbalance_distill_with_warmup: True
distill_start_iter: 50000
