algorithm: fixmatch
resume: True
overwrite: True
use_wandb: True
epoch: 100
num_train_iter: 25000
num_eval_iter: 500
num_log_iter: 250
optim: Adam
lr: 0.002
dataset: small_imagenet127
uratio: 1
batch_size: 64
eval_batch_size: 250
num_labels: 12810
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
ema_m: 0.999
crop_ratio: 0.875
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet50
net_from_name: False
data_dir: ./data
train_sampler: RandomSampler
num_classes: 127
num_workers: 4
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10144
dist_backend: nccl
gpu: None
lb_imb_ratio: 286
ulb_imb_ratio: 286
ulb_num_labels: None
imb_algorithm: crest
crest_num_gens: 5
crest_pro_dist_align: False
crest_alpha: 0.7
crest_dist_align_t: 0.5
