algorithm: supervised
resume: True
overwrite: True
use_wandb: True
epoch: 500
num_train_iter: 250000
num_eval_iter: 500
num_log_iter: 250
optim: Adam
lr: 0.002
dataset: small_imagenet127
batch_size: 64
eval_batch_size: 250
num_labels: 128101
ema_m: 0.999
crop_ratio: 0.875
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet50
net_from_name: False
data_dir: ./data
train_sampler: RandomSampler
num_classes: 127
num_workers: 4
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10132
dist_backend: nccl
gpu: None
include_lb_to_ulb: False
lb_imb_ratio: 286
ulb_imb_ratio: 286
ulb_num_labels: None
